version: '3.7'
services:
  db:
    build: .docker/mysql
    container_name: db
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      # - /var/lib/mysql:/var/lib/mysql
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: projetoY
      MYSQL_ROOT_PASSWORD: "1234"
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION
    networks:
      - app-network
  php:
    build: .docker/php
    container_name: 'php'
    restart: 'always'
    ports:
      - "8081:80"
    links:
      - db
      - redis
    volumes:
      - /var/www/html/logdocker/var/log:/var/log/
      - G:\Projetos Laravel:/var/www/html
    networks: 
      - app-network
  redis:
    image: redis:4.0
    container_name: 'redis'
    restart: 'always'
    command: redis-server --requirepass teste
    ports:
      - "6378:6379"
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local